version: '3.5'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - proxy
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - proxy

networks:
  proxy:
    external: false
    name: proxy
