version: "3.5"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql_db
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mysql_db:
    external: false
    name: mysql_db

volumes:
  mysql-data:
    name: mysql-data
